# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: gigshield
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production tsx server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
